#!/usr/bin/env bash
# Generate compose/projects/.env and bring the projects stack up
# (RabbitMQ + Registry + TellegramService + AI Trading + HomeSecurity).
# Requires the core stack network "nas". Idempotent.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/_common.sh
source "${SCRIPT_DIR}/_common.sh"

require_root
load_config
require_tailscale_ip

if ! docker_ready; then
  die "Docker is not ready. Run scripts/01-install-docker.sh first."
fi

require_nas_network

if [[ "${RABBITMQ_PASS}" == "changeme" ]] || [[ "${REGISTRY_PASS}" == "changeme" ]]; then
  warn "Using default changeme passwords. Set RABBITMQ_PASS and REGISTRY_PASS in config.env."
fi

if [[ -z "${TELEGRAM_BOT_TOKEN}" ]] || [[ -z "${TELEGRAM_CHAT_ID}" ]]; then
  warn "TELEGRAM_BOT_TOKEN / TELEGRAM_CHAT_ID empty in config.env — tellegram will fail until set."
fi

if [[ "${HOMESECURITY_POSTGRES_PASSWORD}" == "changeme" ]]; then
  warn "HOMESECURITY_POSTGRES_PASSWORD is still changeme. Set it in config.env."
fi

"${SCRIPT_DIR}/02-prepare-dirs.sh"
ensure_registry_htpasswd
ensure_insecure_registry
# insecure-registries may restart Docker and stop every container; bring core back first.
if ! docker inspect -f '{{.State.Running}}' portainer 2>/dev/null | grep -qx true; then
  warn "Core containers are not running (often after a Docker restart). Redeploying core first."
  "${SCRIPT_DIR}/03-deploy-stack.sh"
fi
write_projects_compose_env

COMPOSE_FILE="${REPO_ROOT}/compose/projects/docker-compose.yml"
USB_COMPOSE_FILE="${REPO_ROOT}/compose/projects/docker-compose.homesecurity-usb.generated.yml"
ENV_FILE="${REPO_ROOT}/compose/projects/.env"
TELLEGRAM_IMAGE="${TAILSCALE_IP}:${REGISTRY_PORT}/tellegramservice:latest"
cd "${REPO_ROOT}/compose/projects"

USB_COMPOSE_ARGS=()
USB_DEVICES=()
if [[ -n "${HOMESECURITY_USB_CAMERA:-}" && -e "${HOMESECURITY_USB_CAMERA}" ]]; then
  USB_DEVICES+=("${HOMESECURITY_USB_CAMERA}")
fi
for node in /dev/video*; do
  if [[ -c "${node}" ]]; then
    already=0
    for existing in "${USB_DEVICES[@]+"${USB_DEVICES[@]}"}"; do
      if [[ "${existing}" == "${node}" ]]; then
        already=1
        break
      fi
    done
    if [[ "${already}" -eq 0 ]]; then
      USB_DEVICES+=("${node}")
    fi
  fi
done

if [[ ${#USB_DEVICES[@]} -gt 0 ]]; then
  {
    echo "# Generated by 05-deploy-projects.sh — do not edit."
    echo "services:"
    echo "  pipeline:"
    echo "    privileged: true"
    echo "    group_add:"
    echo "      - \"${HOMESECURITY_USB_CAMERA_GID:-44}\""
    echo "    device_cgroup_rules:"
    echo "      - \"c 81:* rmw\""
    echo "    devices:"
    for node in "${USB_DEVICES[@]}"; do
      echo "      - ${node}:${node}"
    done
  } >"${USB_COMPOSE_FILE}"
  USB_COMPOSE_ARGS=(-f "${USB_COMPOSE_FILE}")
  info "USB cameras attached to pipeline: ${USB_DEVICES[*]}"
else
  rm -f "${USB_COMPOSE_FILE}"
  warn "No /dev/video* on this host — Arnos_Room will not have a device"
fi

projects_compose() {
  docker compose -f "${COMPOSE_FILE}" "${USB_COMPOSE_ARGS[@]}" --env-file "${ENV_FILE}" "$@"
}

info "Pulling RabbitMQ + Registry images"
projects_compose pull rabbitmq registry || true

info "Starting RabbitMQ + Registry first (${PROJECTS_COMPOSE_PROJECT_NAME})"
projects_compose up -d rabbitmq registry

info "Logging into private registry ${TAILSCALE_IP}:${REGISTRY_PORT}"
echo "${REGISTRY_PASS}" | docker login "${TAILSCALE_IP}:${REGISTRY_PORT}" \
  -u "${REGISTRY_USER}" --password-stdin

info "Pulling ${TELLEGRAM_IMAGE}"
if projects_compose pull tellegram; then
  info "Starting TellegramService"
  projects_compose up -d tellegram
else
  warn "Could not pull ${TELLEGRAM_IMAGE}"
  warn "Push from your Mac first (bash scripts/build-push-nas.sh), then re-run this script."
fi

AI_TRADING_IMAGE="${TAILSCALE_IP}:${REGISTRY_PORT}/ai-trading:latest"
AI_CFG="${NAS_ROOT}/docker/ai-trading/config.yaml"
if [[ ! -f "${AI_CFG}" ]]; then
  warn "Missing ${AI_CFG}"
  warn "First-time: sudo ./scripts/07-setup-ai-trading.sh   # creates folders + seeds config"
fi

info "Pulling ${AI_TRADING_IMAGE}"
if projects_compose pull ai-trading; then
  info "Starting AI Trading Advisor + Ofelia scheduler"
  projects_compose up -d ai-trading ai-trading-ofelia
else
  warn "Could not pull ${AI_TRADING_IMAGE}"
  warn "On your Mac (AI Trading repo): ./scripts/build-push-nas.sh"
  warn "Then on NAS: sudo ./scripts/07-setup-ai-trading.sh --deploy"
fi

HS_API_IMAGE="${TAILSCALE_IP}:${REGISTRY_PORT}/homesecurity-api:latest"
HS_CAMERAS="${NAS_ROOT}/docker/homesecurity/cameras.yaml"
if [[ ! -f "${HS_CAMERAS}" ]]; then
  warn "Missing ${HS_CAMERAS}"
  warn "First-time: sudo ./scripts/09-setup-homesecurity.sh   # creates folders + seeds cameras.yaml"
fi

info "Pulling HomeSecurity images"
if projects_compose pull api pipeline dashboard; then
  info "Starting HomeSecurity (postgres, redis, api, pipeline, dashboard)"
  projects_compose up -d postgres redis api pipeline dashboard
  if [[ ${#USB_COMPOSE_ARGS[@]} -gt 0 ]]; then
    info "Recreating pipeline with USB devices ${USB_DEVICES[*]}"
    projects_compose up -d --force-recreate pipeline
  fi
else
  warn "Could not pull HomeSecurity images (${HS_API_IMAGE} and siblings)"
  warn "On your Mac (HomeSecuritySystem): ./scripts/build-push-nas.sh"
  warn "Then on NAS: sudo ./scripts/09-setup-homesecurity.sh --deploy"
fi

info "Current containers"
projects_compose ps

echo
info "Projects stack deployed (Tailscale-bound):"
echo "  RabbitMQ AMQP:       ${TAILSCALE_IP}:${RABBITMQ_PORT}"
echo "  RabbitMQ Management: http://${TAILSCALE_IP}:${RABBITMQ_MGMT_PORT}"
echo "  Registry:            http://${TAILSCALE_IP}:${REGISTRY_PORT}"
echo "  TellegramService:    container 'tellegram' on nas network (no host port)"
echo "  Tellegram image:     ${TELLEGRAM_IMAGE}"
echo "  AI Trading:          http://${TAILSCALE_IP}:${AI_TRADING_PORT:-5100}"
echo "  AI Trading image:    ${AI_TRADING_IMAGE}"
echo "  Schedule:            Mon–Fri 07:00 and 19:00 (${TZ})"
echo "  HomeSecurity UI:     LAN http://<nas-lan-ip>:${HOMESECURITY_DASHBOARD_PORT:-8081}"
echo "  HomeSecurity UI:     Tailscale http://${TAILSCALE_IP}:${HOMESECURITY_DASHBOARD_PORT:-8081}"
echo "  HomeSecurity API:    Tailscale http://${TAILSCALE_IP}:${HOMESECURITY_API_PORT:-5101}"
echo "  Recordings path:     ${HOMESECURITY_RECORDINGS_PATH}"
if [[ ${#USB_COMPOSE_ARGS[@]} -gt 0 ]]; then
  echo "  USB cameras:         ${USB_DEVICES[*]} (Arnos_Room)"
fi
echo
echo "  On the nas Docker network: rabbitmq:5672 , registry:5000 , tellegram , ai-trading"
echo "  HomeSecurity uses isolated network 'homesecurity' (api, pipeline, postgres, redis)"
echo "  Reclaim registry disk later: sudo ./scripts/06-registry-gc.sh"
