#!/usr/bin/env bash
# Shared helpers for NAS setup scripts.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${REPO_ROOT}/config.env"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

info() {
  echo "==> $*"
}

warn() {
  echo "WARNING: $*" >&2
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    die "Run as root (sudo). Example: sudo $0"
  fi
}

load_config() {
  if [[ ! -f "${CONFIG_FILE}" ]]; then
    die "Missing ${CONFIG_FILE}. Copy config.env.example to config.env and edit it first."
  fi
  # shellcheck disable=SC1090
  set -a
  source "${CONFIG_FILE}"
  set +a

  : "${NAS_ROOT:?NAS_ROOT must be set in config.env}"
  : "${PUID:=1000}"
  : "${PGID:=100}"
  : "${TZ:=UTC}"
  # MEDIA_PATH is preferred; accept legacy PLEX_MEDIA_PATH if present.
  if [[ -z "${MEDIA_PATH:-}" && -n "${PLEX_MEDIA_PATH:-}" ]]; then
    MEDIA_PATH="${PLEX_MEDIA_PATH}"
  fi
  : "${MEDIA_PATH:=${NAS_ROOT}/media}"
  : "${PORTAINER_PORT:=9000}"
  : "${JELLYFIN_PORT:=8096}"
  : "${VAULTWARDEN_PORT:=8080}"
  : "${VAULTWARDEN_SIGNUPS_ALLOWED:=true}"
  : "${COMPOSE_PROJECT_NAME:=nas}"
  : "${TAILSCALE_IP:=100.92.27.123}"
  : "${PROJECTS_COMPOSE_PROJECT_NAME:=nas-projects}"
  : "${RABBITMQ_PORT:=5672}"
  : "${RABBITMQ_MGMT_PORT:=15672}"
  : "${RABBITMQ_USER:=nas}"
  : "${RABBITMQ_PASS:=changeme}"
  : "${REGISTRY_PORT:=5000}"
  : "${REGISTRY_USER:=nas}"
  : "${REGISTRY_PASS:=changeme}"
  : "${REGISTRY_KEEP_TAGS:=5}"
  : "${TELEGRAM_BOT_TOKEN:=}"
  : "${TELEGRAM_CHAT_ID:=}"
  : "${AI_TRADING_PORT:=5100}"
  : "${GEMINI_API_KEY:=}"
  : "${LOGGING_COMPOSE_PROJECT_NAME:=nas-logging}"
  : "${GRAFANA_PORT:=3000}"
  : "${GRAFANA_ADMIN_USER:=admin}"
  : "${GRAFANA_ADMIN_PASSWORD:=changeme}"
  : "${HOMESECURITY_API_PORT:=5101}"
  : "${HOMESECURITY_DASHBOARD_PORT:=8081}"
  : "${HOMESECURITY_POSTGRES_DB:=homesecurity}"
  : "${HOMESECURITY_POSTGRES_USER:=homesecurity}"
  : "${HOMESECURITY_POSTGRES_PASSWORD:=changeme}"
  : "${HOMESECURITY_RECORDINGS_PATH:=${NAS_ROOT}/docker/homesecurity/recordings}"
  : "${HOMESECURITY_DASHBOARD_LAN_URL:=}"
  : "${HOMESECURITY_TELEGRAM_ENABLED:=true}"
  : "${HOMESECURITY_RETENTION_ENABLED:=true}"
  : "${HOMESECURITY_RETENTION_DAYS:=10}"
  : "${HOMESECURITY_RETENTION_INTERVAL_HOURS:=6}"
  : "${HOMESECURITY_OBJECT_DETECTION_ENABLED:=false}"
  : "${HOMESECURITY_PERSON_TRACKING_ENABLED:=false}"
  : "${HOMESECURITY_FACE_ANALYSIS_ENABLED:=false}"
  : "${HOMESECURITY_YOLO_DEVICE:=cpu}"
}

require_tailscale_ip() {
  : "${TAILSCALE_IP:?TAILSCALE_IP must be set in config.env}"
  if [[ -z "${TAILSCALE_IP}" ]]; then
    die "TAILSCALE_IP is empty. Set it in config.env to your NAS Tailscale IP."
  fi
  if ! ip -4 addr show 2>/dev/null | grep -qF "inet ${TAILSCALE_IP}/"; then
    warn "TAILSCALE_IP ${TAILSCALE_IP} is not present on this host yet."
    warn "Ensure Tailscale is up (tailscale up) before containers can bind to it."
  fi
}

is_omv() {
  [[ -f /etc/default/openmediavault ]] || [[ -x /usr/sbin/omv-salt ]] || command -v omv-confdbadm >/dev/null 2>&1
}

docker_ready() {
  command -v docker >/dev/null 2>&1 || return 1
  docker info >/dev/null 2>&1 || return 1
  docker compose version >/dev/null 2>&1 || return 1
}

require_nas_network() {
  if ! docker network inspect nas >/dev/null 2>&1; then
    die "Docker network 'nas' not found. Deploy the core stack first: sudo ./scripts/03-deploy-stack.sh"
  fi
}

write_compose_env() {
  local out="${REPO_ROOT}/compose/.env"
  cat >"${out}" <<EOF
# Generated by NAS setup scripts — do not edit by hand; change config.env and redeploy.
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
NAS_ROOT=${NAS_ROOT}
PUID=${PUID}
PGID=${PGID}
TZ=${TZ}
MEDIA_PATH=${MEDIA_PATH}
PORTAINER_PORT=${PORTAINER_PORT}
JELLYFIN_PORT=${JELLYFIN_PORT}
VAULTWARDEN_PORT=${VAULTWARDEN_PORT}
VAULTWARDEN_SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}
TAILSCALE_IP=${TAILSCALE_IP}
EOF
  info "Wrote ${out}"
}

write_projects_compose_env() {
  local out="${REPO_ROOT}/compose/projects/.env"
  cat >"${out}" <<EOF
# Generated by NAS setup scripts — do not edit by hand; change config.env and redeploy.
COMPOSE_PROJECT_NAME=${PROJECTS_COMPOSE_PROJECT_NAME}
NAS_ROOT=${NAS_ROOT}
PUID=${PUID}
PGID=${PGID}
TZ=${TZ}
TAILSCALE_IP=${TAILSCALE_IP}
RABBITMQ_PORT=${RABBITMQ_PORT}
RABBITMQ_MGMT_PORT=${RABBITMQ_MGMT_PORT}
RABBITMQ_USER=${RABBITMQ_USER}
RABBITMQ_PASS=${RABBITMQ_PASS}
REGISTRY_PORT=${REGISTRY_PORT}
REGISTRY_USER=${REGISTRY_USER}
REGISTRY_PASS=${REGISTRY_PASS}
REGISTRY_KEEP_TAGS=${REGISTRY_KEEP_TAGS}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
AI_TRADING_PORT=${AI_TRADING_PORT:-5100}
GEMINI_API_KEY=${GEMINI_API_KEY:-}
HOMESECURITY_API_PORT=${HOMESECURITY_API_PORT:-5101}
HOMESECURITY_DASHBOARD_PORT=${HOMESECURITY_DASHBOARD_PORT:-8081}
HOMESECURITY_POSTGRES_DB=${HOMESECURITY_POSTGRES_DB:-homesecurity}
HOMESECURITY_POSTGRES_USER=${HOMESECURITY_POSTGRES_USER:-homesecurity}
HOMESECURITY_POSTGRES_PASSWORD=${HOMESECURITY_POSTGRES_PASSWORD}
HOMESECURITY_RECORDINGS_PATH=${HOMESECURITY_RECORDINGS_PATH}
HOMESECURITY_DASHBOARD_LAN_URL=${HOMESECURITY_DASHBOARD_LAN_URL:-}
HOMESECURITY_TELEGRAM_ENABLED=${HOMESECURITY_TELEGRAM_ENABLED:-true}
HOMESECURITY_RETENTION_ENABLED=${HOMESECURITY_RETENTION_ENABLED:-true}
HOMESECURITY_RETENTION_DAYS=${HOMESECURITY_RETENTION_DAYS:-10}
HOMESECURITY_RETENTION_INTERVAL_HOURS=${HOMESECURITY_RETENTION_INTERVAL_HOURS:-6}
HOMESECURITY_OBJECT_DETECTION_ENABLED=${HOMESECURITY_OBJECT_DETECTION_ENABLED:-false}
HOMESECURITY_PERSON_TRACKING_ENABLED=${HOMESECURITY_PERSON_TRACKING_ENABLED:-false}
HOMESECURITY_FACE_ANALYSIS_ENABLED=${HOMESECURITY_FACE_ANALYSIS_ENABLED:-false}
HOMESECURITY_YOLO_DEVICE=${HOMESECURITY_YOLO_DEVICE:-cpu}
EOF
  info "Wrote ${out}"
}

write_logging_compose_env() {
  local out="${REPO_ROOT}/compose/logging/.env"
  cat >"${out}" <<EOF
# Generated by NAS setup scripts — do not edit by hand; change config.env and redeploy.
COMPOSE_PROJECT_NAME=${LOGGING_COMPOSE_PROJECT_NAME}
NAS_ROOT=${NAS_ROOT}
TZ=${TZ}
TAILSCALE_IP=${TAILSCALE_IP}
GRAFANA_PORT=${GRAFANA_PORT}
GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
EOF
  info "Wrote ${out}"
}

ensure_registry_htpasswd() {
  local auth_dir="${NAS_ROOT}/docker/registry-auth"
  local htpasswd_file="${auth_dir}/htpasswd"
  mkdir -p "${auth_dir}"

  if [[ -f "${htpasswd_file}" ]]; then
    info "Registry htpasswd already exists at ${htpasswd_file}"
    return 0
  fi

  info "Generating registry htpasswd for user ${REGISTRY_USER}"
  if command -v htpasswd >/dev/null 2>&1; then
    htpasswd -Bbc "${htpasswd_file}" "${REGISTRY_USER}" "${REGISTRY_PASS}"
  else
    docker run --rm --entrypoint htpasswd \
      httpd:2 -Bbn "${REGISTRY_USER}" "${REGISTRY_PASS}" >"${htpasswd_file}"
  fi
  chmod 600 "${htpasswd_file}"
  chown root:root "${htpasswd_file}"
}

# Docker pulls images on the host. Private registry is HTTP-only, so the host
# must list ${TAILSCALE_IP}:${REGISTRY_PORT} under insecure-registries.
ensure_insecure_registry() {
  local endpoint="${TAILSCALE_IP}:${REGISTRY_PORT}"
  local daemon_json="/etc/docker/daemon.json"
  local tmp
  tmp="$(mktemp)"

  if [[ ! -f "${daemon_json}" ]]; then
    echo '{}' >"${daemon_json}"
  fi

  if ! python3 - "${daemon_json}" "${endpoint}" "${tmp}" <<'PY'
import json, sys
path, endpoint, out = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path) as f:
    data = json.load(f)
regs = list(data.get("insecure-registries") or [])
changed = False
if endpoint not in regs:
    regs.append(endpoint)
    changed = True
data["insecure-registries"] = regs
with open(out, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
sys.exit(0 if changed else 1)
PY
  then
    info "insecure-registries already includes ${endpoint}"
    rm -f "${tmp}"
    return 0
  fi

  info "Adding ${endpoint} to ${daemon_json} insecure-registries"
  cp "${tmp}" "${daemon_json}"
  rm -f "${tmp}"
  chmod 644 "${daemon_json}"
  info "Restarting Docker to apply insecure-registries"
  systemctl restart docker
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    if docker_ready; then
      break
    fi
    sleep 2
  done
  if ! docker_ready; then
    die "Docker did not come back after restarting for insecure-registries"
  fi
}
