#!/usr/bin/env bash
# Shared helpers for NAS setup scripts.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${REPO_ROOT}/config.env"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

info() {
  echo "==> $*"
}

warn() {
  echo "WARNING: $*" >&2
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    die "Run as root (sudo). Example: sudo $0"
  fi
}

load_config() {
  if [[ ! -f "${CONFIG_FILE}" ]]; then
    die "Missing ${CONFIG_FILE}. Copy config.env.example to config.env and edit it first."
  fi
  # shellcheck disable=SC1090
  set -a
  source "${CONFIG_FILE}"
  set +a

  : "${NAS_ROOT:?NAS_ROOT must be set in config.env}"
  : "${PUID:=1000}"
  : "${PGID:=100}"
  : "${TZ:=UTC}"
  : "${PLEX_MEDIA_PATH:=${NAS_ROOT}/media}"
  : "${PORTAINER_PORT:=9000}"
  : "${PLEX_PORT:=32400}"
  : "${VAULTWARDEN_PORT:=8080}"
  : "${VAULTWARDEN_SIGNUPS_ALLOWED:=true}"
  : "${COMPOSE_PROJECT_NAME:=nas}"
}

is_omv() {
  [[ -f /etc/default/openmediavault ]] || [[ -x /usr/sbin/omv-salt ]] || command -v omv-confdbadm >/dev/null 2>&1
}

docker_ready() {
  command -v docker >/dev/null 2>&1 || return 1
  docker info >/dev/null 2>&1 || return 1
  docker compose version >/dev/null 2>&1 || return 1
}

write_compose_env() {
  local out="${REPO_ROOT}/compose/.env"
  cat >"${out}" <<EOF
# Generated by NAS setup scripts — do not edit by hand; change config.env and redeploy.
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
NAS_ROOT=${NAS_ROOT}
PUID=${PUID}
PGID=${PGID}
TZ=${TZ}
PLEX_MEDIA_PATH=${PLEX_MEDIA_PATH}
PLEX_CLAIM=${PLEX_CLAIM:-}
PORTAINER_PORT=${PORTAINER_PORT}
PLEX_PORT=${PLEX_PORT}
VAULTWARDEN_PORT=${VAULTWARDEN_PORT}
VAULTWARDEN_SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}
EOF
  info "Wrote ${out}"
}
